export type RiskLevel = "Good" | "Moderate" | "Critical" | "Extreme";

export interface LocationData {
  location_name: string;
  location_type: string;
  state_ut: string;
  lng: number;
  lat: number;
  surface_water_pollution_pct: number;
  groundwater_pollution_pct: number;
  risk_level: RiskLevel;
  city_type: string;
  arsenic_as_pct: number;
  chromium_cr_pct: number;
  lead_pb_pct: number;
  cadmium_cd_pct: number;
  zinc_zn_pct: number;
  copper_cu_pct: number;
  nickel_ni_pct: number;
  bod_exceedance_pct: number;
  cod_exceedance_pct: number;
  do_exceedance_pct: number;
  ph_exceedance_pct: number;
  tds_exceedance_pct: number;
  primary_pollutant_source: string;
  key_heavy_metal: string;
}

export interface RiskTier {
  label: string;
  shortLabel: string;
  color: string;
  glow: string;
  textColor: string;
  badgeClass: string;
  dotClass: string;
  borderClass: string;
  bgClass: string;
}

export function getRiskTier(pct: number): RiskTier {
  if (pct >= 50) {
    return {
      label: "Extreme 50%+",
      shortLabel: "Extreme",
      color: "#a855f7",
      glow: "rgba(168,85,247,0.55)",
      textColor: "text-purple-400",
      badgeClass: "bg-purple-500/15 text-purple-300 border-purple-500/40",
      dotClass: "bg-purple-500 shadow-purple-500/50",
      borderClass: "border-purple-500/40",
      bgClass: "bg-purple-500/10",
    };
  }
  if (pct >= 40) {
    return {
      label: "Critical 40-49%",
      shortLabel: "Critical",
      color: "#ef4444",
      glow: "rgba(239,68,68,0.55)",
      textColor: "text-red-400",
      badgeClass: "bg-red-500/15 text-red-300 border-red-500/40",
      dotClass: "bg-red-500 shadow-red-500/50",
      borderClass: "border-red-500/40",
      bgClass: "bg-red-500/10",
    };
  }
  if (pct >= 20) {
    return {
      label: "Moderate 20-39%",
      shortLabel: "Moderate",
      color: "#f59e0b",
      glow: "rgba(245,158,11,0.5)",
      textColor: "text-amber-400",
      badgeClass: "bg-amber-500/15 text-amber-300 border-amber-500/40",
      dotClass: "bg-amber-500 shadow-amber-500/50",
      borderClass: "border-amber-500/40",
      bgClass: "bg-amber-500/10",
    };
  }
  return {
    label: "Good <20%",
    shortLabel: "Good",
    color: "#10b981",
    glow: "rgba(16,185,129,0.5)",
    textColor: "text-emerald-400",
    badgeClass: "bg-emerald-500/15 text-emerald-300 border-emerald-500/40",
    dotClass: "bg-emerald-500 shadow-emerald-500/50",
    borderClass: "border-emerald-500/40",
    bgClass: "bg-emerald-500/10",
  };
}

export function getRiskLevelFromPct(pct: number): RiskLevel {
  if (pct >= 50) return "Extreme";
  if (pct >= 40) return "Critical";
  if (pct >= 20) return "Moderate";
  return "Good";
}

/**
 * Heavy Metal Pollution Index (HPI) — a weighted 0-100 composite of the
 * seven tracked metals plus the overall contamination load. Higher = worse.
 */
export const METALS = [
  { key: "arsenic_as_pct", symbol: "As", name: "Arsenic", color: "#ef4444", who: "0.01 mg/L" },
  { key: "chromium_cr_pct", symbol: "Cr", name: "Chromium", color: "#a855f7", who: "0.05 mg/L" },
  { key: "lead_pb_pct", symbol: "Pb", name: "Lead", color: "#fb923c", who: "0.01 mg/L" },
  { key: "cadmium_cd_pct", symbol: "Cd", name: "Cadmium", color: "#facc15", who: "0.003 mg/L" },
  { key: "zinc_zn_pct", symbol: "Zn", name: "Zinc", color: "#38bdf8", who: "3 mg/L" },
  { key: "copper_cu_pct", symbol: "Cu", name: "Copper", color: "#f97316", who: "2 mg/L" },
  { key: "nickel_ni_pct", symbol: "Ni", name: "Nickel", color: "#818cf8", who: "0.07 mg/L" },
] as const;

// relative toxicity weight of each metal (As, Pb, Cd most toxic)
const METAL_TOXICITY: Record<string, number> = {
  arsenic_as_pct: 1.0,
  cadmium_cd_pct: 0.95,
  lead_pb_pct: 0.9,
  chromium_cr_pct: 0.75,
  nickel_ni_pct: 0.55,
  copper_cu_pct: 0.35,
  zinc_zn_pct: 0.25,
};

export function computeHPI(loc: LocationData): number {
  let weighted = 0;
  let weightSum = 0;
  for (const [key, tox] of Object.entries(METAL_TOXICITY)) {
    const share = (loc as unknown as Record<string, number>)[key] || 0;
    weighted += share * tox;
    weightSum += tox;
  }
  const metalScore = weighted / weightSum; // 0-100 (toxicity-weighted metal share)
  const loadScore = (loc.surface_water_pollution_pct + loc.groundwater_pollution_pct) / 2;
  // blend: 55% overall contamination load, 45% toxicity-weighted metal profile
  return Math.round(loadScore * 0.55 + metalScore * 0.45);
}

export function hpiTier(hpi: number): { label: string; color: string } {
  if (hpi >= 55) return { label: "Critical Index", color: "#a855f7" };
  if (hpi >= 40) return { label: "High Index", color: "#ef4444" };
  if (hpi >= 25) return { label: "Elevated Index", color: "#f59e0b" };
  return { label: "Safe Index", color: "#10b981" };
}

/* ---------- Remediation blueprints (per key metal) ---------- */
export interface Blueprint {
  metal: string;
  stages: { name: string; tech: string }[];
  costPerKL: number; // treatment cost INR per kilolitre
  reductionPct: number; // achievable toxicity reduction
}

export const BLUEPRINTS: Record<string, Blueprint> = {
  Chromium: {
    metal: "Chromium",
    stages: [
      { name: "Reduction", tech: "Catalytic carbon pre-treatment reduces Cr(VI) to Cr(III)" },
      { name: "Ion Exchange", tech: "Strong Base Anion (SBA) resin bed captures chromate ions" },
      { name: "Membrane", tech: "Dual-stage Reverse Osmosis (RO) polishing" },
      { name: "Polishing", tech: "Electrocoagulation to <0.05 mg/L WHO limit" },
    ],
    costPerKL: 42,
    reductionPct: 94,
  },
  Arsenic: {
    metal: "Arsenic",
    stages: [
      { name: "Oxidation", tech: "Pre-oxidation converts As(III) to adsorbable As(V)" },
      { name: "Adsorption", tech: "Activated Alumina + Iron-Oxide Coated Sand (IOCS) bed" },
      { name: "Filtration", tech: "Coagulation-filtration removes arsenic flocs" },
      { name: "Membrane", tech: "Nano-filtration polishing to <10 ppb" },
    ],
    costPerKL: 38,
    reductionPct: 96,
  },
  Lead: {
    metal: "Lead",
    stages: [
      { name: "Ultrafiltration", tech: "Sub-micron UF removes particulate lead" },
      { name: "Membrane", tech: "Thin-film Composite (TFC) Reverse Osmosis" },
      { name: "Softening", tech: "Chelation softening extracts dissolved Pb ions" },
      { name: "Polishing", tech: "Activated carbon removes organic lead complexes" },
    ],
    costPerKL: 40,
    reductionPct: 93,
  },
  Cadmium: {
    metal: "Cadmium",
    stages: [
      { name: "pH Adjust", tech: "Elevate pH to 9.0+ for optimal precipitation" },
      { name: "Precipitation", tech: "Sodium sulfide precipitation of cadmium" },
      { name: "Ion Exchange", tech: "Iminodiacetic-acid chelating resin capture" },
      { name: "Membrane", tech: "Thin-film Composite Reverse Osmosis" },
    ],
    costPerKL: 45,
    reductionPct: 92,
  },
  Zinc: {
    metal: "Zinc",
    stages: [
      { name: "Filtration", tech: "Multi-media sand filtration" },
      { name: "Precipitation", tech: "High-pH chemical precipitation of zinc" },
      { name: "Electrocoagulation", tech: "Aluminium-electrode dissolved zinc removal" },
      { name: "Remineralize", tech: "Post-remineralization restores trace minerals" },
    ],
    costPerKL: 30,
    reductionPct: 90,
  },
  Copper: {
    metal: "Copper",
    stages: [
      { name: "Ion Exchange", tech: "Weak-acid cation resin captures copper" },
      { name: "Microfiltration", tech: "Removes particulate copper" },
      { name: "Softening", tech: "Lime softening + chemical precipitation" },
      { name: "Polishing", tech: "Activated carbon for organo-copper complexes" },
    ],
    costPerKL: 28,
    reductionPct: 91,
  },
  Nickel: {
    metal: "Nickel",
    stages: [
      { name: "Ion Exchange", tech: "Iminodiacetic-acid chelating resin capture" },
      { name: "Precipitation", tech: "Sodium dimethyldithiocarbamate precipitation" },
      { name: "Membrane", tech: "Reverse Osmosis for dissolved nickel" },
      { name: "Tertiary", tech: "Electrocoagulation for discharge compliance" },
    ],
    costPerKL: 36,
    reductionPct: 92,
  },
  Fluoride: {
    metal: "Fluoride",
    stages: [
      { name: "Adsorption", tech: "Activated Alumina defluoridation bed" },
      { name: "Nalgonda", tech: "Alum + lime coagulation of fluoride" },
      { name: "Membrane", tech: "Reverse Osmosis polishing to <1.5 mg/L" },
      { name: "Remineralize", tech: "Calcium remineralization" },
    ],
    costPerKL: 32,
    reductionPct: 93,
  },
};

export function getBlueprint(metal: string): Blueprint {
  return BLUEPRINTS[metal] || BLUEPRINTS["Chromium"];
}

/* ---------- Risk-based mitigation ladder ---------- */
export interface RiskAction {
  tier: RiskLevel;
  goal: string;
  actions: string[];
}

export function getRiskLadder(current: RiskLevel): RiskAction[] {
  const ladder: RiskAction[] = [
    {
      tier: "Extreme",
      goal: "Stabilize & contain",
      actions: [
        "Immediate distribution of point-of-use RO + activated-alumina filters to households",
        "Emergency source substitution — tanker supply from verified safe aquifers",
        "Mandatory industrial effluent audit + zero-liquid-discharge enforcement",
      ],
    },
    {
      tier: "Critical",
      goal: "Reduce to Moderate",
      actions: [
        "Deploy community-scale multi-stage treatment plant at contamination hotspot",
        "Continuous IoT telemetry on intake + discharge points",
        "Bioremediation of riverbed sediment to cut resuspension load",
      ],
    },
    {
      tier: "Moderate",
      goal: "Reduce to Good",
      actions: [
        "Constructed wetlands + phytoremediation buffer along the water body",
        "Municipal sewage treatment upgrade to tertiary standard",
        "Quarterly heavy-metal monitoring with public dashboard reporting",
      ],
    },
    {
      tier: "Good",
      goal: "Maintain safe status",
      actions: [
        "Preventive catchment protection + watershed afforestation",
        "Annual compliance audit to hold below WHO thresholds",
        "Rainwater harvesting to dilute and recharge clean aquifers",
      ],
    },
  ];
  const order: RiskLevel[] = ["Extreme", "Critical", "Moderate", "Good"];
  const startIdx = order.indexOf(current);
  return ladder.filter((l) => order.indexOf(l.tier) >= startIdx);
}

export const locations: LocationData[] = [
  {
    location_name: "Kanpur",
    location_type: "City",
    state_ut: "Uttar Pradesh",
    lng: 80.35,
    lat: 26.45,
    surface_water_pollution_pct: 68,
    groundwater_pollution_pct: 55,
    risk_level: "Extreme",
    city_type: "Industrial (Tannery Hub)",
    arsenic_as_pct: 20,
    chromium_cr_pct: 35,
    lead_pb_pct: 28,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 4,
    copper_cu_pct: 2,
    nickel_ni_pct: 1,
    bod_exceedance_pct: 68,
    cod_exceedance_pct: 67,
    do_exceedance_pct: 54,
    ph_exceedance_pct: 33,
    tds_exceedance_pct: 48,
    primary_pollutant_source: "Tannery effluent (~1000 units) + Ganga discharge",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Lucknow",
    location_type: "City",
    state_ut: "Uttar Pradesh",
    lng: 80.95,
    lat: 26.85,
    surface_water_pollution_pct: 54,
    groundwater_pollution_pct: 48,
    risk_level: "Extreme",
    city_type: "State Capital",
    arsenic_as_pct: 14,
    chromium_cr_pct: 18,
    lead_pb_pct: 34,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 47,
    cod_exceedance_pct: 58,
    do_exceedance_pct: 45,
    ph_exceedance_pct: 29,
    tds_exceedance_pct: 43,
    primary_pollutant_source: "Gomti river urban sewage + auto workshops",
    key_heavy_metal: "Lead",
  },
  {
    location_name: "Varanasi",
    location_type: "City",
    state_ut: "Uttar Pradesh",
    lng: 83,
    lat: 25.32,
    surface_water_pollution_pct: 57,
    groundwater_pollution_pct: 44,
    risk_level: "Extreme",
    city_type: "Religious / Urban",
    arsenic_as_pct: 16,
    chromium_cr_pct: 14,
    lead_pb_pct: 32,
    cadmium_cd_pct: 9,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 5,
    bod_exceedance_pct: 53,
    cod_exceedance_pct: 56,
    do_exceedance_pct: 42,
    ph_exceedance_pct: 31,
    tds_exceedance_pct: 47,
    primary_pollutant_source: "Ganga ritual load + untreated sewage",
    key_heavy_metal: "Lead",
  },
  {
    location_name: "Ghaziabad",
    location_type: "City",
    state_ut: "Uttar Pradesh",
    lng: 77.43,
    lat: 28.67,
    surface_water_pollution_pct: 61,
    groundwater_pollution_pct: 52,
    risk_level: "Extreme",
    city_type: "Industrial",
    arsenic_as_pct: 10,
    chromium_cr_pct: 32,
    lead_pb_pct: 26,
    cadmium_cd_pct: 14,
    zinc_zn_pct: 10,
    copper_cu_pct: 6,
    nickel_ni_pct: 2,
    bod_exceedance_pct: 60,
    cod_exceedance_pct: 65,
    do_exceedance_pct: 47,
    ph_exceedance_pct: 33,
    tds_exceedance_pct: 44,
    primary_pollutant_source: "Hindon river industrial belt",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Agra",
    location_type: "City",
    state_ut: "Uttar Pradesh",
    lng: 78.02,
    lat: 27.18,
    surface_water_pollution_pct: 49,
    groundwater_pollution_pct: 41,
    risk_level: "Critical",
    city_type: "Tourism / Industrial",
    arsenic_as_pct: 12,
    chromium_cr_pct: 30,
    lead_pb_pct: 24,
    cadmium_cd_pct: 12,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 2,
    bod_exceedance_pct: 44,
    cod_exceedance_pct: 47,
    do_exceedance_pct: 35,
    ph_exceedance_pct: 24,
    tds_exceedance_pct: 38,
    primary_pollutant_source: "Yamuna + foundry & petha units",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Meerut",
    location_type: "City",
    state_ut: "Uttar Pradesh",
    lng: 77.7,
    lat: 28.98,
    surface_water_pollution_pct: 47,
    groundwater_pollution_pct: 43,
    risk_level: "Critical",
    city_type: "Industrial",
    arsenic_as_pct: 8,
    chromium_cr_pct: 20,
    lead_pb_pct: 22,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 12,
    copper_cu_pct: 10,
    nickel_ni_pct: 18,
    bod_exceedance_pct: 48,
    cod_exceedance_pct: 45,
    do_exceedance_pct: 38,
    ph_exceedance_pct: 25,
    tds_exceedance_pct: 34,
    primary_pollutant_source: "Electroplating & scissor industry",
    key_heavy_metal: "Nickel",
  },
  {
    location_name: "Prayagraj",
    location_type: "City",
    state_ut: "Uttar Pradesh",
    lng: 81.85,
    lat: 25.44,
    surface_water_pollution_pct: 46,
    groundwater_pollution_pct: 38,
    risk_level: "Critical",
    city_type: "Religious / Urban",
    arsenic_as_pct: 14,
    chromium_cr_pct: 16,
    lead_pb_pct: 30,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 46,
    cod_exceedance_pct: 49,
    do_exceedance_pct: 35,
    ph_exceedance_pct: 27,
    tds_exceedance_pct: 32,
    primary_pollutant_source: "Sangam confluence + sewage",
    key_heavy_metal: "Lead",
  },
  {
    location_name: "Gorakhpur",
    location_type: "City",
    state_ut: "Uttar Pradesh",
    lng: 83.37,
    lat: 26.76,
    surface_water_pollution_pct: 34,
    groundwater_pollution_pct: 42,
    risk_level: "Critical",
    city_type: "Urban",
    arsenic_as_pct: 42,
    chromium_cr_pct: 10,
    lead_pb_pct: 14,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 14,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 34,
    cod_exceedance_pct: 37,
    do_exceedance_pct: 25,
    ph_exceedance_pct: 23,
    tds_exceedance_pct: 28,
    primary_pollutant_source: "Shallow aquifer arsenic belt",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "New Delhi",
    location_type: "City",
    state_ut: "Delhi",
    lng: 77.21,
    lat: 28.61,
    surface_water_pollution_pct: 58,
    groundwater_pollution_pct: 50,
    risk_level: "Extreme",
    city_type: "National Capital",
    arsenic_as_pct: 10,
    chromium_cr_pct: 18,
    lead_pb_pct: 34,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 14,
    copper_cu_pct: 12,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 57,
    cod_exceedance_pct: 62,
    do_exceedance_pct: 44,
    ph_exceedance_pct: 32,
    tds_exceedance_pct: 42,
    primary_pollutant_source: "Yamuna Najafgarh drain + traffic",
    key_heavy_metal: "Lead",
  },
  {
    location_name: "Delhi (Okhla)",
    location_type: "City",
    state_ut: "Delhi",
    lng: 77.28,
    lat: 28.53,
    surface_water_pollution_pct: 63,
    groundwater_pollution_pct: 49,
    risk_level: "Extreme",
    city_type: "Industrial",
    arsenic_as_pct: 8,
    chromium_cr_pct: 34,
    lead_pb_pct: 24,
    cadmium_cd_pct: 12,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 2,
    bod_exceedance_pct: 64,
    cod_exceedance_pct: 67,
    do_exceedance_pct: 48,
    ph_exceedance_pct: 28,
    tds_exceedance_pct: 48,
    primary_pollutant_source: "Okhla industrial effluent + Yamuna",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Faridabad",
    location_type: "City",
    state_ut: "Haryana",
    lng: 77.31,
    lat: 28.41,
    surface_water_pollution_pct: 44,
    groundwater_pollution_pct: 40,
    risk_level: "Critical",
    city_type: "Industrial",
    arsenic_as_pct: 8,
    chromium_cr_pct: 18,
    lead_pb_pct: 20,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 14,
    copper_cu_pct: 12,
    nickel_ni_pct: 20,
    bod_exceedance_pct: 44,
    cod_exceedance_pct: 47,
    do_exceedance_pct: 33,
    ph_exceedance_pct: 27,
    tds_exceedance_pct: 32,
    primary_pollutant_source: "Electroplating & auto components",
    key_heavy_metal: "Nickel",
  },
  {
    location_name: "Gurugram",
    location_type: "City",
    state_ut: "Haryana",
    lng: 77.03,
    lat: 28.46,
    surface_water_pollution_pct: 33,
    groundwater_pollution_pct: 37,
    risk_level: "Moderate",
    city_type: "Urban / IT",
    arsenic_as_pct: 6,
    chromium_cr_pct: 30,
    lead_pb_pct: 22,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 16,
    copper_cu_pct: 12,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 30,
    cod_exceedance_pct: 31,
    do_exceedance_pct: 22,
    ph_exceedance_pct: 21,
    tds_exceedance_pct: 34,
    primary_pollutant_source: "Sewage + peripheral industry",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Panipat",
    location_type: "City",
    state_ut: "Haryana",
    lng: 76.97,
    lat: 29.39,
    surface_water_pollution_pct: 46,
    groundwater_pollution_pct: 42,
    risk_level: "Critical",
    city_type: "Industrial (Textile)",
    arsenic_as_pct: 8,
    chromium_cr_pct: 32,
    lead_pb_pct: 20,
    cadmium_cd_pct: 12,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 40,
    cod_exceedance_pct: 49,
    do_exceedance_pct: 39,
    ph_exceedance_pct: 25,
    tds_exceedance_pct: 37,
    primary_pollutant_source: "Textile dyeing effluent",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Chandigarh",
    location_type: "City",
    state_ut: "Chandigarh",
    lng: 76.78,
    lat: 30.73,
    surface_water_pollution_pct: 28,
    groundwater_pollution_pct: 26,
    risk_level: "Moderate",
    city_type: "UT Capital",
    arsenic_as_pct: 6,
    chromium_cr_pct: 14,
    lead_pb_pct: 18,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 20,
    copper_cu_pct: 26,
    nickel_ni_pct: 8,
    bod_exceedance_pct: 22,
    cod_exceedance_pct: 25,
    do_exceedance_pct: 22,
    ph_exceedance_pct: 11,
    tds_exceedance_pct: 23,
    primary_pollutant_source: "Urban runoff + minor industry",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Ludhiana",
    location_type: "City",
    state_ut: "Punjab",
    lng: 75.85,
    lat: 30.9,
    surface_water_pollution_pct: 52,
    groundwater_pollution_pct: 46,
    risk_level: "Extreme",
    city_type: "Industrial (Hosiery)",
    arsenic_as_pct: 8,
    chromium_cr_pct: 20,
    lead_pb_pct: 18,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 12,
    copper_cu_pct: 12,
    nickel_ni_pct: 20,
    bod_exceedance_pct: 48,
    cod_exceedance_pct: 51,
    do_exceedance_pct: 38,
    ph_exceedance_pct: 29,
    tds_exceedance_pct: 46,
    primary_pollutant_source: "Electroplating & dyeing (Buddha Nala)",
    key_heavy_metal: "Nickel",
  },
  {
    location_name: "Amritsar",
    location_type: "City",
    state_ut: "Punjab",
    lng: 74.87,
    lat: 31.63,
    surface_water_pollution_pct: 38,
    groundwater_pollution_pct: 40,
    risk_level: "Critical",
    city_type: "Urban",
    arsenic_as_pct: 36,
    chromium_cr_pct: 12,
    lead_pb_pct: 16,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 35,
    cod_exceedance_pct: 36,
    do_exceedance_pct: 26,
    ph_exceedance_pct: 23,
    tds_exceedance_pct: 37,
    primary_pollutant_source: "Sewage + shallow aquifer",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "Jalandhar",
    location_type: "City",
    state_ut: "Punjab",
    lng: 75.58,
    lat: 31.33,
    surface_water_pollution_pct: 41,
    groundwater_pollution_pct: 39,
    risk_level: "Critical",
    city_type: "Industrial",
    arsenic_as_pct: 10,
    chromium_cr_pct: 30,
    lead_pb_pct: 20,
    cadmium_cd_pct: 12,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 41,
    cod_exceedance_pct: 44,
    do_exceedance_pct: 31,
    ph_exceedance_pct: 25,
    tds_exceedance_pct: 30,
    primary_pollutant_source: "Leather & sports goods effluent",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Bathinda",
    location_type: "City",
    state_ut: "Punjab",
    lng: 74.95,
    lat: 30.21,
    surface_water_pollution_pct: 30,
    groundwater_pollution_pct: 44,
    risk_level: "Critical",
    city_type: "Semi-arid",
    arsenic_as_pct: 40,
    chromium_cr_pct: 10,
    lead_pb_pct: 14,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 28,
    cod_exceedance_pct: 28,
    do_exceedance_pct: 20,
    ph_exceedance_pct: 20,
    tds_exceedance_pct: 35,
    primary_pollutant_source: "Uranium & arsenic groundwater belt",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "Jaipur",
    location_type: "City",
    state_ut: "Rajasthan",
    lng: 75.79,
    lat: 26.91,
    surface_water_pollution_pct: 39,
    groundwater_pollution_pct: 41,
    risk_level: "Critical",
    city_type: "State Capital",
    arsenic_as_pct: 24,
    chromium_cr_pct: 16,
    lead_pb_pct: 20,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 12,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 40,
    cod_exceedance_pct: 37,
    do_exceedance_pct: 31,
    ph_exceedance_pct: 22,
    tds_exceedance_pct: 30,
    primary_pollutant_source: "Urban sewage + hard groundwater",
    key_heavy_metal: "Fluoride",
  },
  {
    location_name: "Jodhpur",
    location_type: "City",
    state_ut: "Rajasthan",
    lng: 73.02,
    lat: 26.24,
    surface_water_pollution_pct: 43,
    groundwater_pollution_pct: 45,
    risk_level: "Critical",
    city_type: "Industrial (Textile)",
    arsenic_as_pct: 14,
    chromium_cr_pct: 34,
    lead_pb_pct: 16,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 12,
    copper_cu_pct: 10,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 37,
    cod_exceedance_pct: 46,
    do_exceedance_pct: 36,
    ph_exceedance_pct: 24,
    tds_exceedance_pct: 37,
    primary_pollutant_source: "Textile dyeing + arid aquifer",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Udaipur",
    location_type: "City",
    state_ut: "Rajasthan",
    lng: 73.71,
    lat: 24.58,
    surface_water_pollution_pct: 34,
    groundwater_pollution_pct: 32,
    risk_level: "Moderate",
    city_type: "Tourism / Mining",
    arsenic_as_pct: 8,
    chromium_cr_pct: 14,
    lead_pb_pct: 14,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 34,
    copper_cu_pct: 16,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 28,
    cod_exceedance_pct: 37,
    do_exceedance_pct: 29,
    ph_exceedance_pct: 21,
    tds_exceedance_pct: 28,
    primary_pollutant_source: "Zinc smelting & lake catchment",
    key_heavy_metal: "Zinc",
  },
  {
    location_name: "Kota",
    location_type: "City",
    state_ut: "Rajasthan",
    lng: 75.83,
    lat: 25.21,
    surface_water_pollution_pct: 41,
    groundwater_pollution_pct: 38,
    risk_level: "Critical",
    city_type: "Industrial",
    arsenic_as_pct: 10,
    chromium_cr_pct: 16,
    lead_pb_pct: 18,
    cadmium_cd_pct: 30,
    zinc_zn_pct: 14,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 36,
    cod_exceedance_pct: 39,
    do_exceedance_pct: 29,
    ph_exceedance_pct: 20,
    tds_exceedance_pct: 34,
    primary_pollutant_source: "Chambal + chemical units",
    key_heavy_metal: "Cadmium",
  },
  {
    location_name: "Bikaner",
    location_type: "City",
    state_ut: "Rajasthan",
    lng: 73.31,
    lat: 28.02,
    surface_water_pollution_pct: 29,
    groundwater_pollution_pct: 46,
    risk_level: "Critical",
    city_type: "Arid",
    arsenic_as_pct: 38,
    chromium_cr_pct: 12,
    lead_pb_pct: 14,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 24,
    cod_exceedance_pct: 31,
    do_exceedance_pct: 25,
    ph_exceedance_pct: 19,
    tds_exceedance_pct: 32,
    primary_pollutant_source: "Deep arid groundwater",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "Ahmedabad",
    location_type: "City",
    state_ut: "Gujarat",
    lng: 72.57,
    lat: 23.03,
    surface_water_pollution_pct: 56,
    groundwater_pollution_pct: 47,
    risk_level: "Extreme",
    city_type: "Metropolitan / Industrial",
    arsenic_as_pct: 10,
    chromium_cr_pct: 34,
    lead_pb_pct: 20,
    cadmium_cd_pct: 14,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 2,
    bod_exceedance_pct: 55,
    cod_exceedance_pct: 60,
    do_exceedance_pct: 43,
    ph_exceedance_pct: 31,
    tds_exceedance_pct: 40,
    primary_pollutant_source: "Sabarmati + Vatva/Naroda estates",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Surat",
    location_type: "City",
    state_ut: "Gujarat",
    lng: 72.83,
    lat: 21.17,
    surface_water_pollution_pct: 59,
    groundwater_pollution_pct: 44,
    risk_level: "Extreme",
    city_type: "Industrial (Textile/Dye)",
    arsenic_as_pct: 8,
    chromium_cr_pct: 36,
    lead_pb_pct: 18,
    cadmium_cd_pct: 14,
    zinc_zn_pct: 12,
    copper_cu_pct: 10,
    nickel_ni_pct: 2,
    bod_exceedance_pct: 56,
    cod_exceedance_pct: 63,
    do_exceedance_pct: 45,
    ph_exceedance_pct: 29,
    tds_exceedance_pct: 48,
    primary_pollutant_source: "Dyeing & printing effluent (Tapi)",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Vadodara",
    location_type: "City",
    state_ut: "Gujarat",
    lng: 73.19,
    lat: 22.31,
    surface_water_pollution_pct: 51,
    groundwater_pollution_pct: 43,
    risk_level: "Extreme",
    city_type: "Industrial (Chemical)",
    arsenic_as_pct: 10,
    chromium_cr_pct: 20,
    lead_pb_pct: 18,
    cadmium_cd_pct: 28,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 47,
    cod_exceedance_pct: 50,
    do_exceedance_pct: 37,
    ph_exceedance_pct: 28,
    tds_exceedance_pct: 44,
    primary_pollutant_source: "Petrochemical & chemical estates",
    key_heavy_metal: "Cadmium",
  },
  {
    location_name: "Rajkot",
    location_type: "City",
    state_ut: "Gujarat",
    lng: 70.8,
    lat: 22.3,
    surface_water_pollution_pct: 42,
    groundwater_pollution_pct: 45,
    risk_level: "Critical",
    city_type: "Industrial",
    arsenic_as_pct: 8,
    chromium_cr_pct: 18,
    lead_pb_pct: 18,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 12,
    nickel_ni_pct: 20,
    bod_exceedance_pct: 43,
    cod_exceedance_pct: 40,
    do_exceedance_pct: 34,
    ph_exceedance_pct: 23,
    tds_exceedance_pct: 33,
    primary_pollutant_source: "Engineering & casting units",
    key_heavy_metal: "Nickel",
  },
  {
    location_name: "Bhavnagar",
    location_type: "City",
    state_ut: "Gujarat",
    lng: 72.15,
    lat: 21.76,
    surface_water_pollution_pct: 39,
    groundwater_pollution_pct: 41,
    risk_level: "Critical",
    city_type: "Coastal / Industrial",
    arsenic_as_pct: 10,
    chromium_cr_pct: 16,
    lead_pb_pct: 34,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 12,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 39,
    cod_exceedance_pct: 42,
    do_exceedance_pct: 29,
    ph_exceedance_pct: 25,
    tds_exceedance_pct: 30,
    primary_pollutant_source: "Ship-breaking & alang belt",
    key_heavy_metal: "Lead",
  },
  {
    location_name: "Vapi",
    location_type: "City",
    state_ut: "Gujarat",
    lng: 72.9,
    lat: 20.37,
    surface_water_pollution_pct: 64,
    groundwater_pollution_pct: 52,
    risk_level: "Extreme",
    city_type: "Industrial (Chemical)",
    arsenic_as_pct: 10,
    chromium_cr_pct: 20,
    lead_pb_pct: 18,
    cadmium_cd_pct: 30,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 2,
    bod_exceedance_pct: 58,
    cod_exceedance_pct: 63,
    do_exceedance_pct: 47,
    ph_exceedance_pct: 30,
    tds_exceedance_pct: 49,
    primary_pollutant_source: "Vapi GIDC chemical corridor",
    key_heavy_metal: "Cadmium",
  },
  {
    location_name: "Mumbai",
    location_type: "City",
    state_ut: "Maharashtra",
    lng: 72.87,
    lat: 19.08,
    surface_water_pollution_pct: 55,
    groundwater_pollution_pct: 44,
    risk_level: "Extreme",
    city_type: "Metropolitan",
    arsenic_as_pct: 10,
    chromium_cr_pct: 16,
    lead_pb_pct: 34,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 12,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 55,
    cod_exceedance_pct: 54,
    do_exceedance_pct: 44,
    ph_exceedance_pct: 28,
    tds_exceedance_pct: 38,
    primary_pollutant_source: "Mithi river + coastal discharge",
    key_heavy_metal: "Lead",
  },
  {
    location_name: "Pune",
    location_type: "City",
    state_ut: "Maharashtra",
    lng: 73.86,
    lat: 18.52,
    surface_water_pollution_pct: 44,
    groundwater_pollution_pct: 40,
    risk_level: "Critical",
    city_type: "Metropolitan / IT",
    arsenic_as_pct: 8,
    chromium_cr_pct: 32,
    lead_pb_pct: 22,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 39,
    cod_exceedance_pct: 42,
    do_exceedance_pct: 31,
    ph_exceedance_pct: 22,
    tds_exceedance_pct: 36,
    primary_pollutant_source: "Mula-Mutha + Pimpri industry",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Nagpur",
    location_type: "City",
    state_ut: "Maharashtra",
    lng: 79.09,
    lat: 21.15,
    surface_water_pollution_pct: 37,
    groundwater_pollution_pct: 39,
    risk_level: "Moderate",
    city_type: "Urban",
    arsenic_as_pct: 8,
    chromium_cr_pct: 14,
    lead_pb_pct: 18,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 32,
    copper_cu_pct: 14,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 38,
    cod_exceedance_pct: 35,
    do_exceedance_pct: 30,
    ph_exceedance_pct: 21,
    tds_exceedance_pct: 28,
    primary_pollutant_source: "Nag river + urban runoff",
    key_heavy_metal: "Zinc",
  },
  {
    location_name: "Nashik",
    location_type: "City",
    state_ut: "Maharashtra",
    lng: 73.79,
    lat: 20,
    surface_water_pollution_pct: 41,
    groundwater_pollution_pct: 38,
    risk_level: "Critical",
    city_type: "Industrial",
    arsenic_as_pct: 8,
    chromium_cr_pct: 30,
    lead_pb_pct: 20,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 16,
    copper_cu_pct: 12,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 42,
    cod_exceedance_pct: 39,
    do_exceedance_pct: 33,
    ph_exceedance_pct: 22,
    tds_exceedance_pct: 30,
    primary_pollutant_source: "Godavari + MIDC estates",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Aurangabad",
    location_type: "City",
    state_ut: "Maharashtra",
    lng: 75.34,
    lat: 19.88,
    surface_water_pollution_pct: 39,
    groundwater_pollution_pct: 42,
    risk_level: "Critical",
    city_type: "Industrial",
    arsenic_as_pct: 8,
    chromium_cr_pct: 18,
    lead_pb_pct: 18,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 12,
    nickel_ni_pct: 20,
    bod_exceedance_pct: 32,
    cod_exceedance_pct: 37,
    do_exceedance_pct: 31,
    ph_exceedance_pct: 16,
    tds_exceedance_pct: 34,
    primary_pollutant_source: "Auto & pharma cluster",
    key_heavy_metal: "Nickel",
  },
  {
    location_name: "Nanded",
    location_type: "City",
    state_ut: "Maharashtra",
    lng: 77.31,
    lat: 19.15,
    surface_water_pollution_pct: 31,
    groundwater_pollution_pct: 36,
    risk_level: "Moderate",
    city_type: "Urban",
    arsenic_as_pct: 34,
    chromium_cr_pct: 12,
    lead_pb_pct: 16,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 32,
    cod_exceedance_pct: 29,
    do_exceedance_pct: 25,
    ph_exceedance_pct: 18,
    tds_exceedance_pct: 24,
    primary_pollutant_source: "Godavari basin sewage",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "Bengaluru",
    location_type: "City",
    state_ut: "Karnataka",
    lng: 77.59,
    lat: 12.97,
    surface_water_pollution_pct: 42,
    groundwater_pollution_pct: 40,
    risk_level: "Critical",
    city_type: "State Capital / IT Hub",
    arsenic_as_pct: 6,
    chromium_cr_pct: 34,
    lead_pb_pct: 22,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 16,
    copper_cu_pct: 10,
    nickel_ni_pct: 2,
    bod_exceedance_pct: 42,
    cod_exceedance_pct: 45,
    do_exceedance_pct: 32,
    ph_exceedance_pct: 26,
    tds_exceedance_pct: 31,
    primary_pollutant_source: "Peenya estate + lake pollution",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Mysuru",
    location_type: "City",
    state_ut: "Karnataka",
    lng: 76.65,
    lat: 12.3,
    surface_water_pollution_pct: 29,
    groundwater_pollution_pct: 31,
    risk_level: "Moderate",
    city_type: "Tourism / Urban",
    arsenic_as_pct: 6,
    chromium_cr_pct: 14,
    lead_pb_pct: 18,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 20,
    copper_cu_pct: 28,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 31,
    cod_exceedance_pct: 26,
    do_exceedance_pct: 23,
    ph_exceedance_pct: 18,
    tds_exceedance_pct: 22,
    primary_pollutant_source: "Sewage + minor industry",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Mangaluru",
    location_type: "City",
    state_ut: "Karnataka",
    lng: 74.86,
    lat: 12.91,
    surface_water_pollution_pct: 34,
    groundwater_pollution_pct: 33,
    risk_level: "Moderate",
    city_type: "Coastal / Industrial",
    arsenic_as_pct: 8,
    chromium_cr_pct: 14,
    lead_pb_pct: 16,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 34,
    copper_cu_pct: 14,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 34,
    cod_exceedance_pct: 37,
    do_exceedance_pct: 25,
    ph_exceedance_pct: 23,
    tds_exceedance_pct: 24,
    primary_pollutant_source: "Chemical & fertilizer plants",
    key_heavy_metal: "Zinc",
  },
  {
    location_name: "Hubballi",
    location_type: "City",
    state_ut: "Karnataka",
    lng: 75.12,
    lat: 15.36,
    surface_water_pollution_pct: 28,
    groundwater_pollution_pct: 30,
    risk_level: "Moderate",
    city_type: "Urban",
    arsenic_as_pct: 6,
    chromium_cr_pct: 16,
    lead_pb_pct: 18,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 18,
    copper_cu_pct: 28,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 26,
    cod_exceedance_pct: 25,
    do_exceedance_pct: 18,
    ph_exceedance_pct: 19,
    tds_exceedance_pct: 29,
    primary_pollutant_source: "Urban runoff",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Ballari",
    location_type: "City",
    state_ut: "Karnataka",
    lng: 76.92,
    lat: 15.14,
    surface_water_pollution_pct: 44,
    groundwater_pollution_pct: 41,
    risk_level: "Critical",
    city_type: "Mining",
    arsenic_as_pct: 8,
    chromium_cr_pct: 16,
    lead_pb_pct: 16,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 34,
    copper_cu_pct: 12,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 38,
    cod_exceedance_pct: 47,
    do_exceedance_pct: 37,
    ph_exceedance_pct: 25,
    tds_exceedance_pct: 36,
    primary_pollutant_source: "Iron-ore mining runoff",
    key_heavy_metal: "Zinc",
  },
  {
    location_name: "Chennai",
    location_type: "City",
    state_ut: "Tamil Nadu",
    lng: 80.27,
    lat: 13.08,
    surface_water_pollution_pct: 47,
    groundwater_pollution_pct: 39,
    risk_level: "Critical",
    city_type: "Metropolitan",
    arsenic_as_pct: 10,
    chromium_cr_pct: 18,
    lead_pb_pct: 32,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 12,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 41,
    cod_exceedance_pct: 50,
    do_exceedance_pct: 40,
    ph_exceedance_pct: 26,
    tds_exceedance_pct: 37,
    primary_pollutant_source: "Cooum & Adyar + Ambattur estate",
    key_heavy_metal: "Lead",
  },
  {
    location_name: "Coimbatore",
    location_type: "City",
    state_ut: "Tamil Nadu",
    lng: 76.96,
    lat: 11.02,
    surface_water_pollution_pct: 41,
    groundwater_pollution_pct: 37,
    risk_level: "Critical",
    city_type: "Industrial (Textile)",
    arsenic_as_pct: 8,
    chromium_cr_pct: 34,
    lead_pb_pct: 18,
    cadmium_cd_pct: 12,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 34,
    cod_exceedance_pct: 39,
    do_exceedance_pct: 33,
    ph_exceedance_pct: 16,
    tds_exceedance_pct: 33,
    primary_pollutant_source: "Noyyal dyeing effluent",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Madurai",
    location_type: "City",
    state_ut: "Tamil Nadu",
    lng: 78.12,
    lat: 9.93,
    surface_water_pollution_pct: 34,
    groundwater_pollution_pct: 33,
    risk_level: "Moderate",
    city_type: "Urban",
    arsenic_as_pct: 8,
    chromium_cr_pct: 30,
    lead_pb_pct: 20,
    cadmium_cd_pct: 12,
    zinc_zn_pct: 14,
    copper_cu_pct: 12,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 28,
    cod_exceedance_pct: 37,
    do_exceedance_pct: 29,
    ph_exceedance_pct: 21,
    tds_exceedance_pct: 28,
    primary_pollutant_source: "Vaigai + tannery units",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Tiruppur",
    location_type: "City",
    state_ut: "Tamil Nadu",
    lng: 77.35,
    lat: 11.11,
    surface_water_pollution_pct: 58,
    groundwater_pollution_pct: 45,
    risk_level: "Extreme",
    city_type: "Industrial (Dyeing)",
    arsenic_as_pct: 8,
    chromium_cr_pct: 38,
    lead_pb_pct: 16,
    cadmium_cd_pct: 12,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 2,
    bod_exceedance_pct: 54,
    cod_exceedance_pct: 57,
    do_exceedance_pct: 42,
    ph_exceedance_pct: 31,
    tds_exceedance_pct: 48,
    primary_pollutant_source: "Knitwear dyeing (Noyyal)",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Vellore",
    location_type: "City",
    state_ut: "Tamil Nadu",
    lng: 79.13,
    lat: 12.92,
    surface_water_pollution_pct: 54,
    groundwater_pollution_pct: 46,
    risk_level: "Extreme",
    city_type: "Industrial (Tannery)",
    arsenic_as_pct: 10,
    chromium_cr_pct: 38,
    lead_pb_pct: 16,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 2,
    bod_exceedance_pct: 47,
    cod_exceedance_pct: 58,
    do_exceedance_pct: 45,
    ph_exceedance_pct: 29,
    tds_exceedance_pct: 43,
    primary_pollutant_source: "Palar tannery cluster (Ambur/Ranipet)",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Salem",
    location_type: "City",
    state_ut: "Tamil Nadu",
    lng: 78.15,
    lat: 11.66,
    surface_water_pollution_pct: 37,
    groundwater_pollution_pct: 36,
    risk_level: "Moderate",
    city_type: "Industrial",
    arsenic_as_pct: 8,
    chromium_cr_pct: 18,
    lead_pb_pct: 16,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 12,
    nickel_ni_pct: 22,
    bod_exceedance_pct: 35,
    cod_exceedance_pct: 40,
    do_exceedance_pct: 28,
    ph_exceedance_pct: 20,
    tds_exceedance_pct: 35,
    primary_pollutant_source: "Steel & magnesite units",
    key_heavy_metal: "Nickel",
  },
  {
    location_name: "Hyderabad",
    location_type: "City",
    state_ut: "Telangana",
    lng: 78.47,
    lat: 17.39,
    surface_water_pollution_pct: 45,
    groundwater_pollution_pct: 41,
    risk_level: "Critical",
    city_type: "State Capital / IT",
    arsenic_as_pct: 10,
    chromium_cr_pct: 18,
    lead_pb_pct: 30,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 12,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 45,
    cod_exceedance_pct: 48,
    do_exceedance_pct: 34,
    ph_exceedance_pct: 27,
    tds_exceedance_pct: 33,
    primary_pollutant_source: "Musi river + Patancheru estate",
    key_heavy_metal: "Lead",
  },
  {
    location_name: "Warangal",
    location_type: "City",
    state_ut: "Telangana",
    lng: 79.6,
    lat: 17.98,
    surface_water_pollution_pct: 32,
    groundwater_pollution_pct: 35,
    risk_level: "Moderate",
    city_type: "Urban",
    arsenic_as_pct: 8,
    chromium_cr_pct: 30,
    lead_pb_pct: 20,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 16,
    copper_cu_pct: 12,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 29,
    cod_exceedance_pct: 30,
    do_exceedance_pct: 22,
    ph_exceedance_pct: 21,
    tds_exceedance_pct: 32,
    primary_pollutant_source: "Sewage + minor industry",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Nizamabad",
    location_type: "City",
    state_ut: "Telangana",
    lng: 78.09,
    lat: 18.67,
    surface_water_pollution_pct: 30,
    groundwater_pollution_pct: 38,
    risk_level: "Moderate",
    city_type: "Urban / Agri",
    arsenic_as_pct: 34,
    chromium_cr_pct: 12,
    lead_pb_pct: 16,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 31,
    cod_exceedance_pct: 33,
    do_exceedance_pct: 22,
    ph_exceedance_pct: 21,
    tds_exceedance_pct: 25,
    primary_pollutant_source: "Groundwater arsenic + agri runoff",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "Visakhapatnam",
    location_type: "City",
    state_ut: "Andhra Pradesh",
    lng: 83.22,
    lat: 17.69,
    surface_water_pollution_pct: 49,
    groundwater_pollution_pct: 42,
    risk_level: "Critical",
    city_type: "Industrial (Port)",
    arsenic_as_pct: 10,
    chromium_cr_pct: 20,
    lead_pb_pct: 18,
    cadmium_cd_pct: 28,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 51,
    cod_exceedance_pct: 52,
    do_exceedance_pct: 37,
    ph_exceedance_pct: 23,
    tds_exceedance_pct: 39,
    primary_pollutant_source: "Steel plant & port effluent",
    key_heavy_metal: "Cadmium",
  },
  {
    location_name: "Vijayawada",
    location_type: "City",
    state_ut: "Andhra Pradesh",
    lng: 80.65,
    lat: 16.51,
    surface_water_pollution_pct: 37,
    groundwater_pollution_pct: 38,
    risk_level: "Moderate",
    city_type: "Urban",
    arsenic_as_pct: 10,
    chromium_cr_pct: 16,
    lead_pb_pct: 32,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 12,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 30,
    cod_exceedance_pct: 35,
    do_exceedance_pct: 30,
    ph_exceedance_pct: 15,
    tds_exceedance_pct: 32,
    primary_pollutant_source: "Krishna + urban discharge",
    key_heavy_metal: "Lead",
  },
  {
    location_name: "Guntur",
    location_type: "City",
    state_ut: "Andhra Pradesh",
    lng: 80.44,
    lat: 16.31,
    surface_water_pollution_pct: 33,
    groundwater_pollution_pct: 40,
    risk_level: "Critical",
    city_type: "Agri / Urban",
    arsenic_as_pct: 34,
    chromium_cr_pct: 12,
    lead_pb_pct: 16,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 34,
    cod_exceedance_pct: 31,
    do_exceedance_pct: 26,
    ph_exceedance_pct: 19,
    tds_exceedance_pct: 27,
    primary_pollutant_source: "Agri runoff + shallow aquifer",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "Tirupati",
    location_type: "City",
    state_ut: "Andhra Pradesh",
    lng: 79.42,
    lat: 13.63,
    surface_water_pollution_pct: 26,
    groundwater_pollution_pct: 28,
    risk_level: "Moderate",
    city_type: "Tourism",
    arsenic_as_pct: 6,
    chromium_cr_pct: 14,
    lead_pb_pct: 18,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 20,
    copper_cu_pct: 28,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 24,
    cod_exceedance_pct: 23,
    do_exceedance_pct: 17,
    ph_exceedance_pct: 18,
    tds_exceedance_pct: 27,
    primary_pollutant_source: "Urban runoff",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Kolkata",
    location_type: "City",
    state_ut: "West Bengal",
    lng: 88.36,
    lat: 22.57,
    surface_water_pollution_pct: 53,
    groundwater_pollution_pct: 58,
    risk_level: "Extreme",
    city_type: "Metropolitan",
    arsenic_as_pct: 44,
    chromium_cr_pct: 10,
    lead_pb_pct: 14,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 46,
    cod_exceedance_pct: 57,
    do_exceedance_pct: 44,
    ph_exceedance_pct: 28,
    tds_exceedance_pct: 47,
    primary_pollutant_source: "Hooghly + Gangetic arsenic aquifer",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "Howrah",
    location_type: "City",
    state_ut: "West Bengal",
    lng: 88.31,
    lat: 22.59,
    surface_water_pollution_pct: 57,
    groundwater_pollution_pct: 56,
    risk_level: "Extreme",
    city_type: "Industrial",
    arsenic_as_pct: 40,
    chromium_cr_pct: 14,
    lead_pb_pct: 14,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 57,
    cod_exceedance_pct: 56,
    do_exceedance_pct: 46,
    ph_exceedance_pct: 29,
    tds_exceedance_pct: 44,
    primary_pollutant_source: "Hooghly industrial belt + arsenic",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "Durgapur",
    location_type: "City",
    state_ut: "West Bengal",
    lng: 87.31,
    lat: 23.55,
    surface_water_pollution_pct: 51,
    groundwater_pollution_pct: 44,
    risk_level: "Extreme",
    city_type: "Industrial (Steel)",
    arsenic_as_pct: 12,
    chromium_cr_pct: 20,
    lead_pb_pct: 18,
    cadmium_cd_pct: 26,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 47,
    cod_exceedance_pct: 50,
    do_exceedance_pct: 37,
    ph_exceedance_pct: 28,
    tds_exceedance_pct: 44,
    primary_pollutant_source: "Steel & coke effluent (Damodar)",
    key_heavy_metal: "Cadmium",
  },
  {
    location_name: "Asansol",
    location_type: "City",
    state_ut: "West Bengal",
    lng: 86.99,
    lat: 23.68,
    surface_water_pollution_pct: 48,
    groundwater_pollution_pct: 45,
    risk_level: "Critical",
    city_type: "Industrial (Coal)",
    arsenic_as_pct: 12,
    chromium_cr_pct: 16,
    lead_pb_pct: 32,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 42,
    cod_exceedance_pct: 51,
    do_exceedance_pct: 40,
    ph_exceedance_pct: 26,
    tds_exceedance_pct: 40,
    primary_pollutant_source: "Coal & steel belt",
    key_heavy_metal: "Lead",
  },
  {
    location_name: "Siliguri",
    location_type: "City",
    state_ut: "West Bengal",
    lng: 88.43,
    lat: 26.73,
    surface_water_pollution_pct: 30,
    groundwater_pollution_pct: 36,
    risk_level: "Moderate",
    city_type: "Urban",
    arsenic_as_pct: 36,
    chromium_cr_pct: 12,
    lead_pb_pct: 16,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 28,
    cod_exceedance_pct: 28,
    do_exceedance_pct: 20,
    ph_exceedance_pct: 20,
    tds_exceedance_pct: 32,
    primary_pollutant_source: "Terai arsenic aquifer",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "Patna",
    location_type: "City",
    state_ut: "Bihar",
    lng: 85.14,
    lat: 25.61,
    surface_water_pollution_pct: 44,
    groundwater_pollution_pct: 54,
    risk_level: "Extreme",
    city_type: "State Capital",
    arsenic_as_pct: 46,
    chromium_cr_pct: 10,
    lead_pb_pct: 14,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 10,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 42,
    cod_exceedance_pct: 47,
    do_exceedance_pct: 33,
    ph_exceedance_pct: 23,
    tds_exceedance_pct: 46,
    primary_pollutant_source: "Ganga arsenic belt + sewage",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "Gaya",
    location_type: "City",
    state_ut: "Bihar",
    lng: 85,
    lat: 24.79,
    surface_water_pollution_pct: 33,
    groundwater_pollution_pct: 42,
    risk_level: "Critical",
    city_type: "Urban",
    arsenic_as_pct: 42,
    chromium_cr_pct: 10,
    lead_pb_pct: 16,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 28,
    cod_exceedance_pct: 31,
    do_exceedance_pct: 22,
    ph_exceedance_pct: 17,
    tds_exceedance_pct: 32,
    primary_pollutant_source: "Falgu + arsenic aquifer",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "Bhagalpur",
    location_type: "City",
    state_ut: "Bihar",
    lng: 86.98,
    lat: 25.24,
    surface_water_pollution_pct: 35,
    groundwater_pollution_pct: 48,
    risk_level: "Critical",
    city_type: "Urban / Silk",
    arsenic_as_pct: 42,
    chromium_cr_pct: 14,
    lead_pb_pct: 14,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 12,
    copper_cu_pct: 6,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 35,
    cod_exceedance_pct: 38,
    do_exceedance_pct: 26,
    ph_exceedance_pct: 23,
    tds_exceedance_pct: 31,
    primary_pollutant_source: "Ganga arsenic + silk dyeing",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "Muzaffarpur",
    location_type: "City",
    state_ut: "Bihar",
    lng: 85.39,
    lat: 26.12,
    surface_water_pollution_pct: 31,
    groundwater_pollution_pct: 46,
    risk_level: "Critical",
    city_type: "Urban / Agri",
    arsenic_as_pct: 44,
    chromium_cr_pct: 10,
    lead_pb_pct: 14,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 27,
    cod_exceedance_pct: 34,
    do_exceedance_pct: 27,
    ph_exceedance_pct: 13,
    tds_exceedance_pct: 37,
    primary_pollutant_source: "Shallow arsenic aquifer",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "Ranchi",
    location_type: "City",
    state_ut: "Jharkhand",
    lng: 85.31,
    lat: 23.34,
    surface_water_pollution_pct: 42,
    groundwater_pollution_pct: 44,
    risk_level: "Critical",
    city_type: "State Capital / Mining",
    arsenic_as_pct: 12,
    chromium_cr_pct: 16,
    lead_pb_pct: 32,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 43,
    cod_exceedance_pct: 40,
    do_exceedance_pct: 34,
    ph_exceedance_pct: 23,
    tds_exceedance_pct: 33,
    primary_pollutant_source: "Mining runoff + urban discharge",
    key_heavy_metal: "Lead",
  },
  {
    location_name: "Jamshedpur",
    location_type: "City",
    state_ut: "Jharkhand",
    lng: 86.2,
    lat: 22.8,
    surface_water_pollution_pct: 54,
    groundwater_pollution_pct: 46,
    risk_level: "Extreme",
    city_type: "Industrial (Steel)",
    arsenic_as_pct: 12,
    chromium_cr_pct: 20,
    lead_pb_pct: 18,
    cadmium_cd_pct: 26,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 46,
    cod_exceedance_pct: 53,
    do_exceedance_pct: 43,
    ph_exceedance_pct: 22,
    tds_exceedance_pct: 43,
    primary_pollutant_source: "Steel city effluent (Subarnarekha)",
    key_heavy_metal: "Cadmium",
  },
  {
    location_name: "Dhanbad",
    location_type: "City",
    state_ut: "Jharkhand",
    lng: 86.43,
    lat: 23.8,
    surface_water_pollution_pct: 50,
    groundwater_pollution_pct: 48,
    risk_level: "Extreme",
    city_type: "Mining (Coal)",
    arsenic_as_pct: 12,
    chromium_cr_pct: 16,
    lead_pb_pct: 34,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 12,
    copper_cu_pct: 10,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 44,
    cod_exceedance_pct: 54,
    do_exceedance_pct: 42,
    ph_exceedance_pct: 27,
    tds_exceedance_pct: 42,
    primary_pollutant_source: "Coal mining & washery discharge",
    key_heavy_metal: "Lead",
  },
  {
    location_name: "Bokaro",
    location_type: "City",
    state_ut: "Jharkhand",
    lng: 85.99,
    lat: 23.67,
    surface_water_pollution_pct: 47,
    groundwater_pollution_pct: 44,
    risk_level: "Critical",
    city_type: "Industrial (Steel)",
    arsenic_as_pct: 10,
    chromium_cr_pct: 20,
    lead_pb_pct: 18,
    cadmium_cd_pct: 28,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 48,
    cod_exceedance_pct: 45,
    do_exceedance_pct: 38,
    ph_exceedance_pct: 25,
    tds_exceedance_pct: 35,
    primary_pollutant_source: "Steel plant effluent",
    key_heavy_metal: "Cadmium",
  },
  {
    location_name: "Bhopal",
    location_type: "City",
    state_ut: "Madhya Pradesh",
    lng: 77.41,
    lat: 23.26,
    surface_water_pollution_pct: 36,
    groundwater_pollution_pct: 38,
    risk_level: "Moderate",
    city_type: "State Capital",
    arsenic_as_pct: 10,
    chromium_cr_pct: 18,
    lead_pb_pct: 18,
    cadmium_cd_pct: 28,
    zinc_zn_pct: 14,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 37,
    cod_exceedance_pct: 34,
    do_exceedance_pct: 29,
    ph_exceedance_pct: 20,
    tds_exceedance_pct: 27,
    primary_pollutant_source: "Upper lake + Union Carbide legacy",
    key_heavy_metal: "Cadmium",
  },
  {
    location_name: "Indore",
    location_type: "City",
    state_ut: "Madhya Pradesh",
    lng: 75.86,
    lat: 22.72,
    surface_water_pollution_pct: 41,
    groundwater_pollution_pct: 40,
    risk_level: "Critical",
    city_type: "Industrial",
    arsenic_as_pct: 8,
    chromium_cr_pct: 32,
    lead_pb_pct: 20,
    cadmium_cd_pct: 12,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 42,
    cod_exceedance_pct: 39,
    do_exceedance_pct: 33,
    ph_exceedance_pct: 22,
    tds_exceedance_pct: 30,
    primary_pollutant_source: "Khan river + Pithampur estate",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Jabalpur",
    location_type: "City",
    state_ut: "Madhya Pradesh",
    lng: 79.99,
    lat: 23.18,
    surface_water_pollution_pct: 32,
    groundwater_pollution_pct: 34,
    risk_level: "Moderate",
    city_type: "Urban",
    arsenic_as_pct: 8,
    chromium_cr_pct: 14,
    lead_pb_pct: 18,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 18,
    copper_cu_pct: 28,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 29,
    cod_exceedance_pct: 30,
    do_exceedance_pct: 22,
    ph_exceedance_pct: 21,
    tds_exceedance_pct: 32,
    primary_pollutant_source: "Narmada + urban runoff",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Gwalior",
    location_type: "City",
    state_ut: "Madhya Pradesh",
    lng: 78.18,
    lat: 26.22,
    surface_water_pollution_pct: 38,
    groundwater_pollution_pct: 39,
    risk_level: "Moderate",
    city_type: "Urban / Industrial",
    arsenic_as_pct: 8,
    chromium_cr_pct: 30,
    lead_pb_pct: 20,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 16,
    copper_cu_pct: 12,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 32,
    cod_exceedance_pct: 41,
    do_exceedance_pct: 32,
    ph_exceedance_pct: 22,
    tds_exceedance_pct: 33,
    primary_pollutant_source: "Sewage + industrial estate",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Bhubaneswar",
    location_type: "City",
    state_ut: "Odisha",
    lng: 85.82,
    lat: 20.3,
    surface_water_pollution_pct: 31,
    groundwater_pollution_pct: 34,
    risk_level: "Moderate",
    city_type: "State Capital",
    arsenic_as_pct: 8,
    chromium_cr_pct: 14,
    lead_pb_pct: 18,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 32,
    copper_cu_pct: 14,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 27,
    cod_exceedance_pct: 34,
    do_exceedance_pct: 27,
    ph_exceedance_pct: 13,
    tds_exceedance_pct: 32,
    primary_pollutant_source: "Urban runoff + minor industry",
    key_heavy_metal: "Zinc",
  },
  {
    location_name: "Cuttack",
    location_type: "City",
    state_ut: "Odisha",
    lng: 85.88,
    lat: 20.46,
    surface_water_pollution_pct: 34,
    groundwater_pollution_pct: 37,
    risk_level: "Moderate",
    city_type: "Urban",
    arsenic_as_pct: 10,
    chromium_cr_pct: 16,
    lead_pb_pct: 32,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 28,
    cod_exceedance_pct: 37,
    do_exceedance_pct: 29,
    ph_exceedance_pct: 21,
    tds_exceedance_pct: 30,
    primary_pollutant_source: "Mahanadi + urban discharge",
    key_heavy_metal: "Lead",
  },
  {
    location_name: "Rourkela",
    location_type: "City",
    state_ut: "Odisha",
    lng: 84.85,
    lat: 22.26,
    surface_water_pollution_pct: 48,
    groundwater_pollution_pct: 43,
    risk_level: "Critical",
    city_type: "Industrial (Steel)",
    arsenic_as_pct: 10,
    chromium_cr_pct: 20,
    lead_pb_pct: 18,
    cadmium_cd_pct: 28,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 45,
    cod_exceedance_pct: 46,
    do_exceedance_pct: 34,
    ph_exceedance_pct: 27,
    tds_exceedance_pct: 43,
    primary_pollutant_source: "Steel plant effluent (Brahmani)",
    key_heavy_metal: "Cadmium",
  },
  {
    location_name: "Angul",
    location_type: "City",
    state_ut: "Odisha",
    lng: 85.1,
    lat: 20.84,
    surface_water_pollution_pct: 46,
    groundwater_pollution_pct: 42,
    risk_level: "Critical",
    city_type: "Industrial (Power/Aluminium)",
    arsenic_as_pct: 8,
    chromium_cr_pct: 16,
    lead_pb_pct: 16,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 34,
    copper_cu_pct: 12,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 44,
    cod_exceedance_pct: 49,
    do_exceedance_pct: 35,
    ph_exceedance_pct: 23,
    tds_exceedance_pct: 41,
    primary_pollutant_source: "Aluminium & thermal power",
    key_heavy_metal: "Zinc",
  },
  {
    location_name: "Guwahati",
    location_type: "City",
    state_ut: "Assam",
    lng: 91.75,
    lat: 26.14,
    surface_water_pollution_pct: 34,
    groundwater_pollution_pct: 44,
    risk_level: "Critical",
    city_type: "Urban / Gateway",
    arsenic_as_pct: 42,
    chromium_cr_pct: 10,
    lead_pb_pct: 16,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 31,
    cod_exceedance_pct: 32,
    do_exceedance_pct: 23,
    ph_exceedance_pct: 22,
    tds_exceedance_pct: 37,
    primary_pollutant_source: "Brahmaputra + arsenic aquifer",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "Dibrugarh",
    location_type: "City",
    state_ut: "Assam",
    lng: 94.9,
    lat: 27.47,
    surface_water_pollution_pct: 32,
    groundwater_pollution_pct: 46,
    risk_level: "Critical",
    city_type: "Oil / Tea",
    arsenic_as_pct: 44,
    chromium_cr_pct: 10,
    lead_pb_pct: 14,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 32,
    cod_exceedance_pct: 35,
    do_exceedance_pct: 24,
    ph_exceedance_pct: 22,
    tds_exceedance_pct: 29,
    primary_pollutant_source: "Oil fields + arsenic groundwater",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "Silchar",
    location_type: "City",
    state_ut: "Assam",
    lng: 92.79,
    lat: 24.83,
    surface_water_pollution_pct: 28,
    groundwater_pollution_pct: 40,
    risk_level: "Critical",
    city_type: "Urban",
    arsenic_as_pct: 40,
    chromium_cr_pct: 10,
    lead_pb_pct: 16,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 14,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 23,
    cod_exceedance_pct: 30,
    do_exceedance_pct: 24,
    ph_exceedance_pct: 18,
    tds_exceedance_pct: 29,
    primary_pollutant_source: "Barak valley aquifer",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "Raipur",
    location_type: "City",
    state_ut: "Chhattisgarh",
    lng: 81.63,
    lat: 21.25,
    surface_water_pollution_pct: 39,
    groundwater_pollution_pct: 38,
    risk_level: "Moderate",
    city_type: "State Capital / Industrial",
    arsenic_as_pct: 8,
    chromium_cr_pct: 32,
    lead_pb_pct: 20,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 16,
    copper_cu_pct: 10,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 40,
    cod_exceedance_pct: 37,
    do_exceedance_pct: 31,
    ph_exceedance_pct: 22,
    tds_exceedance_pct: 29,
    primary_pollutant_source: "Steel & sponge-iron belt",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Bhilai",
    location_type: "City",
    state_ut: "Chhattisgarh",
    lng: 81.38,
    lat: 21.19,
    surface_water_pollution_pct: 45,
    groundwater_pollution_pct: 42,
    risk_level: "Critical",
    city_type: "Industrial (Steel)",
    arsenic_as_pct: 10,
    chromium_cr_pct: 20,
    lead_pb_pct: 18,
    cadmium_cd_pct: 28,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 46,
    cod_exceedance_pct: 43,
    do_exceedance_pct: 36,
    ph_exceedance_pct: 24,
    tds_exceedance_pct: 33,
    primary_pollutant_source: "Steel plant effluent",
    key_heavy_metal: "Cadmium",
  },
  {
    location_name: "Korba",
    location_type: "City",
    state_ut: "Chhattisgarh",
    lng: 82.72,
    lat: 22.35,
    surface_water_pollution_pct: 43,
    groundwater_pollution_pct: 40,
    risk_level: "Critical",
    city_type: "Industrial (Power/Coal)",
    arsenic_as_pct: 12,
    chromium_cr_pct: 16,
    lead_pb_pct: 32,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 41,
    cod_exceedance_pct: 46,
    do_exceedance_pct: 32,
    ph_exceedance_pct: 22,
    tds_exceedance_pct: 39,
    primary_pollutant_source: "Thermal power & coal ash",
    key_heavy_metal: "Lead",
  },
  {
    location_name: "Thiruvananthapuram",
    location_type: "City",
    state_ut: "Kerala",
    lng: 76.94,
    lat: 8.52,
    surface_water_pollution_pct: 22,
    groundwater_pollution_pct: 24,
    risk_level: "Moderate",
    city_type: "State Capital",
    arsenic_as_pct: 6,
    chromium_cr_pct: 14,
    lead_pb_pct: 18,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 18,
    copper_cu_pct: 28,
    nickel_ni_pct: 8,
    bod_exceedance_pct: 20,
    cod_exceedance_pct: 19,
    do_exceedance_pct: 18,
    ph_exceedance_pct: 17,
    tds_exceedance_pct: 16,
    primary_pollutant_source: "Urban runoff",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Kochi",
    location_type: "City",
    state_ut: "Kerala",
    lng: 76.27,
    lat: 9.93,
    surface_water_pollution_pct: 34,
    groundwater_pollution_pct: 29,
    risk_level: "Moderate",
    city_type: "Coastal / Industrial",
    arsenic_as_pct: 10,
    chromium_cr_pct: 18,
    lead_pb_pct: 18,
    cadmium_cd_pct: 28,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 32,
    cod_exceedance_pct: 37,
    do_exceedance_pct: 25,
    ph_exceedance_pct: 19,
    tds_exceedance_pct: 31,
    primary_pollutant_source: "Eloor-Edayar chemical belt",
    key_heavy_metal: "Cadmium",
  },
  {
    location_name: "Kozhikode",
    location_type: "City",
    state_ut: "Kerala",
    lng: 75.78,
    lat: 11.25,
    surface_water_pollution_pct: 21,
    groundwater_pollution_pct: 23,
    risk_level: "Moderate",
    city_type: "Coastal / Urban",
    arsenic_as_pct: 6,
    chromium_cr_pct: 14,
    lead_pb_pct: 18,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 18,
    copper_cu_pct: 28,
    nickel_ni_pct: 8,
    bod_exceedance_pct: 22,
    cod_exceedance_pct: 23,
    do_exceedance_pct: 15,
    ph_exceedance_pct: 17,
    tds_exceedance_pct: 15,
    primary_pollutant_source: "Urban runoff",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Kollam",
    location_type: "City",
    state_ut: "Kerala",
    lng: 76.6,
    lat: 8.89,
    surface_water_pollution_pct: 24,
    groundwater_pollution_pct: 26,
    risk_level: "Moderate",
    city_type: "Coastal",
    arsenic_as_pct: 8,
    chromium_cr_pct: 14,
    lead_pb_pct: 16,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 32,
    copper_cu_pct: 14,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 26,
    cod_exceedance_pct: 21,
    do_exceedance_pct: 19,
    ph_exceedance_pct: 16,
    tds_exceedance_pct: 17,
    primary_pollutant_source: "Mineral sands & urban runoff",
    key_heavy_metal: "Zinc",
  },
  {
    location_name: "Panaji",
    location_type: "City",
    state_ut: "Goa",
    lng: 73.83,
    lat: 15.5,
    surface_water_pollution_pct: 19,
    groundwater_pollution_pct: 22,
    risk_level: "Moderate",
    city_type: "UT Capital / Tourism",
    arsenic_as_pct: 6,
    chromium_cr_pct: 14,
    lead_pb_pct: 16,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 18,
    copper_cu_pct: 30,
    nickel_ni_pct: 8,
    bod_exceedance_pct: 21,
    cod_exceedance_pct: 16,
    do_exceedance_pct: 15,
    ph_exceedance_pct: 14,
    tds_exceedance_pct: 13,
    primary_pollutant_source: "Tourism & mining runoff",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Vasco da Gama",
    location_type: "City",
    state_ut: "Goa",
    lng: 73.81,
    lat: 15.4,
    surface_water_pollution_pct: 26,
    groundwater_pollution_pct: 27,
    risk_level: "Moderate",
    city_type: "Port / Mining",
    arsenic_as_pct: 8,
    chromium_cr_pct: 14,
    lead_pb_pct: 16,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 34,
    copper_cu_pct: 14,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 29,
    cod_exceedance_pct: 28,
    do_exceedance_pct: 19,
    ph_exceedance_pct: 13,
    tds_exceedance_pct: 23,
    primary_pollutant_source: "Iron-ore port & mining",
    key_heavy_metal: "Zinc",
  },
  {
    location_name: "Dehradun",
    location_type: "City",
    state_ut: "Uttarakhand",
    lng: 78.03,
    lat: 30.32,
    surface_water_pollution_pct: 24,
    groundwater_pollution_pct: 26,
    risk_level: "Moderate",
    city_type: "State Capital",
    arsenic_as_pct: 6,
    chromium_cr_pct: 14,
    lead_pb_pct: 18,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 18,
    copper_cu_pct: 28,
    nickel_ni_pct: 8,
    bod_exceedance_pct: 22,
    cod_exceedance_pct: 21,
    do_exceedance_pct: 15,
    ph_exceedance_pct: 18,
    tds_exceedance_pct: 25,
    primary_pollutant_source: "Urban runoff + minor industry",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Haridwar",
    location_type: "City",
    state_ut: "Uttarakhand",
    lng: 78.16,
    lat: 29.95,
    surface_water_pollution_pct: 33,
    groundwater_pollution_pct: 31,
    risk_level: "Moderate",
    city_type: "Religious / Industrial",
    arsenic_as_pct: 8,
    chromium_cr_pct: 30,
    lead_pb_pct: 20,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 16,
    copper_cu_pct: 12,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 30,
    cod_exceedance_pct: 31,
    do_exceedance_pct: 22,
    ph_exceedance_pct: 21,
    tds_exceedance_pct: 31,
    primary_pollutant_source: "Ganga ritual load + SIDCUL estate",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Haldwani",
    location_type: "City",
    state_ut: "Uttarakhand",
    lng: 79.51,
    lat: 29.22,
    surface_water_pollution_pct: 22,
    groundwater_pollution_pct: 28,
    risk_level: "Moderate",
    city_type: "Urban / Foothill",
    arsenic_as_pct: 8,
    chromium_cr_pct: 18,
    lead_pb_pct: 18,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 12,
    nickel_ni_pct: 20,
    bod_exceedance_pct: 20,
    cod_exceedance_pct: 19,
    do_exceedance_pct: 14,
    ph_exceedance_pct: 17,
    tds_exceedance_pct: 25,
    primary_pollutant_source: "Foothill industry",
    key_heavy_metal: "Nickel",
  },
  {
    location_name: "Shimla",
    location_type: "City",
    state_ut: "Himachal Pradesh",
    lng: 77.17,
    lat: 31.1,
    surface_water_pollution_pct: 15,
    groundwater_pollution_pct: 17,
    risk_level: "Good",
    city_type: "State Capital / Hill",
    arsenic_as_pct: 6,
    chromium_cr_pct: 14,
    lead_pb_pct: 16,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 18,
    copper_cu_pct: 30,
    nickel_ni_pct: 8,
    bod_exceedance_pct: 17,
    cod_exceedance_pct: 12,
    do_exceedance_pct: 12,
    ph_exceedance_pct: 12,
    tds_exceedance_pct: 10,
    primary_pollutant_source: "Tourism & urban runoff",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Baddi",
    location_type: "City",
    state_ut: "Himachal Pradesh",
    lng: 76.79,
    lat: 30.96,
    surface_water_pollution_pct: 41,
    groundwater_pollution_pct: 38,
    risk_level: "Critical",
    city_type: "Industrial (Pharma)",
    arsenic_as_pct: 10,
    chromium_cr_pct: 18,
    lead_pb_pct: 18,
    cadmium_cd_pct: 28,
    zinc_zn_pct: 14,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 39,
    cod_exceedance_pct: 44,
    do_exceedance_pct: 31,
    ph_exceedance_pct: 21,
    tds_exceedance_pct: 38,
    primary_pollutant_source: "Pharma & chemical estate",
    key_heavy_metal: "Cadmium",
  },
  {
    location_name: "Mandi",
    location_type: "City",
    state_ut: "Himachal Pradesh",
    lng: 76.93,
    lat: 31.71,
    surface_water_pollution_pct: 13,
    groundwater_pollution_pct: 15,
    risk_level: "Good",
    city_type: "Hill Town",
    arsenic_as_pct: 6,
    chromium_cr_pct: 12,
    lead_pb_pct: 14,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 18,
    copper_cu_pct: 32,
    nickel_ni_pct: 10,
    bod_exceedance_pct: 12,
    cod_exceedance_pct: 15,
    do_exceedance_pct: 8,
    ph_exceedance_pct: 10,
    tds_exceedance_pct: 16,
    primary_pollutant_source: "Minimal — hill runoff",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Srinagar",
    location_type: "City",
    state_ut: "Jammu and Kashmir",
    lng: 74.8,
    lat: 34.08,
    surface_water_pollution_pct: 18,
    groundwater_pollution_pct: 20,
    risk_level: "Moderate",
    city_type: "UT Capital",
    arsenic_as_pct: 8,
    chromium_cr_pct: 14,
    lead_pb_pct: 16,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 18,
    copper_cu_pct: 28,
    nickel_ni_pct: 8,
    bod_exceedance_pct: 16,
    cod_exceedance_pct: 15,
    do_exceedance_pct: 10,
    ph_exceedance_pct: 15,
    tds_exceedance_pct: 20,
    primary_pollutant_source: "Dal lake + urban runoff",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Jammu",
    location_type: "City",
    state_ut: "Jammu and Kashmir",
    lng: 74.86,
    lat: 32.73,
    surface_water_pollution_pct: 21,
    groundwater_pollution_pct: 23,
    risk_level: "Moderate",
    city_type: "Winter Capital",
    arsenic_as_pct: 8,
    chromium_cr_pct: 14,
    lead_pb_pct: 16,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 30,
    copper_cu_pct: 16,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 20,
    cod_exceedance_pct: 23,
    do_exceedance_pct: 15,
    ph_exceedance_pct: 13,
    tds_exceedance_pct: 23,
    primary_pollutant_source: "Tawi river + urban runoff",
    key_heavy_metal: "Zinc",
  },
  {
    location_name: "Leh",
    location_type: "City",
    state_ut: "Ladakh",
    lng: 77.58,
    lat: 34.15,
    surface_water_pollution_pct: 12,
    groundwater_pollution_pct: 8,
    risk_level: "Good",
    city_type: "UT Capital / High Altitude",
    arsenic_as_pct: 8,
    chromium_cr_pct: 10,
    lead_pb_pct: 10,
    cadmium_cd_pct: 6,
    zinc_zn_pct: 18,
    copper_cu_pct: 32,
    nickel_ni_pct: 16,
    bod_exceedance_pct: 15,
    cod_exceedance_pct: 14,
    do_exceedance_pct: 12,
    ph_exceedance_pct: 8,
    tds_exceedance_pct: 5,
    primary_pollutant_source: "High altitude — minimal pollution",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Kargil",
    location_type: "City",
    state_ut: "Ladakh",
    lng: 76.13,
    lat: 34.56,
    surface_water_pollution_pct: 10,
    groundwater_pollution_pct: 7,
    risk_level: "Good",
    city_type: "High Altitude",
    arsenic_as_pct: 8,
    chromium_cr_pct: 10,
    lead_pb_pct: 10,
    cadmium_cd_pct: 6,
    zinc_zn_pct: 18,
    copper_cu_pct: 34,
    nickel_ni_pct: 14,
    bod_exceedance_pct: 13,
    cod_exceedance_pct: 7,
    do_exceedance_pct: 8,
    ph_exceedance_pct: 10,
    tds_exceedance_pct: 4,
    primary_pollutant_source: "Minimal — glacial melt",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Gangtok",
    location_type: "City",
    state_ut: "Sikkim",
    lng: 88.61,
    lat: 27.33,
    surface_water_pollution_pct: 9,
    groundwater_pollution_pct: 11,
    risk_level: "Good",
    city_type: "State Capital / Hill",
    arsenic_as_pct: 6,
    chromium_cr_pct: 12,
    lead_pb_pct: 14,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 18,
    copper_cu_pct: 34,
    nickel_ni_pct: 8,
    bod_exceedance_pct: 5,
    cod_exceedance_pct: 10,
    do_exceedance_pct: 9,
    ph_exceedance_pct: 11,
    tds_exceedance_pct: 9,
    primary_pollutant_source: "Minimal — hill runoff",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Itanagar",
    location_type: "City",
    state_ut: "Arunachal Pradesh",
    lng: 93.61,
    lat: 27.1,
    surface_water_pollution_pct: 13,
    groundwater_pollution_pct: 14,
    risk_level: "Good",
    city_type: "State Capital / Hill",
    arsenic_as_pct: 6,
    chromium_cr_pct: 12,
    lead_pb_pct: 14,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 18,
    copper_cu_pct: 34,
    nickel_ni_pct: 8,
    bod_exceedance_pct: 11,
    cod_exceedance_pct: 10,
    do_exceedance_pct: 6,
    ph_exceedance_pct: 13,
    tds_exceedance_pct: 15,
    primary_pollutant_source: "Minimal — forest runoff",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Imphal",
    location_type: "City",
    state_ut: "Manipur",
    lng: 93.94,
    lat: 24.82,
    surface_water_pollution_pct: 16,
    groundwater_pollution_pct: 18,
    risk_level: "Good",
    city_type: "State Capital",
    arsenic_as_pct: 8,
    chromium_cr_pct: 14,
    lead_pb_pct: 16,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 32,
    copper_cu_pct: 14,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 18,
    cod_exceedance_pct: 13,
    do_exceedance_pct: 13,
    ph_exceedance_pct: 12,
    tds_exceedance_pct: 10,
    primary_pollutant_source: "Urban runoff + Loktak catchment",
    key_heavy_metal: "Zinc",
  },
  {
    location_name: "Aizawl",
    location_type: "City",
    state_ut: "Mizoram",
    lng: 92.72,
    lat: 23.73,
    surface_water_pollution_pct: 11,
    groundwater_pollution_pct: 13,
    risk_level: "Good",
    city_type: "State Capital / Hill",
    arsenic_as_pct: 6,
    chromium_cr_pct: 12,
    lead_pb_pct: 14,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 18,
    copper_cu_pct: 34,
    nickel_ni_pct: 8,
    bod_exceedance_pct: 13,
    cod_exceedance_pct: 8,
    do_exceedance_pct: 9,
    ph_exceedance_pct: 10,
    tds_exceedance_pct: 6,
    primary_pollutant_source: "Minimal — hill runoff",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Kohima",
    location_type: "City",
    state_ut: "Nagaland",
    lng: 94.11,
    lat: 25.67,
    surface_water_pollution_pct: 13,
    groundwater_pollution_pct: 15,
    risk_level: "Good",
    city_type: "State Capital / Hill",
    arsenic_as_pct: 6,
    chromium_cr_pct: 12,
    lead_pb_pct: 14,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 18,
    copper_cu_pct: 34,
    nickel_ni_pct: 8,
    bod_exceedance_pct: 15,
    cod_exceedance_pct: 10,
    do_exceedance_pct: 10,
    ph_exceedance_pct: 11,
    tds_exceedance_pct: 8,
    primary_pollutant_source: "Minimal — hill runoff",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Dimapur",
    location_type: "City",
    state_ut: "Nagaland",
    lng: 93.73,
    lat: 25.9,
    surface_water_pollution_pct: 21,
    groundwater_pollution_pct: 24,
    risk_level: "Moderate",
    city_type: "Urban",
    arsenic_as_pct: 8,
    chromium_cr_pct: 14,
    lead_pb_pct: 16,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 30,
    copper_cu_pct: 16,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 16,
    cod_exceedance_pct: 23,
    do_exceedance_pct: 19,
    ph_exceedance_pct: 15,
    tds_exceedance_pct: 19,
    primary_pollutant_source: "Urban runoff + minor industry",
    key_heavy_metal: "Zinc",
  },
  {
    location_name: "Shillong",
    location_type: "City",
    state_ut: "Meghalaya",
    lng: 91.88,
    lat: 25.58,
    surface_water_pollution_pct: 17,
    groundwater_pollution_pct: 19,
    risk_level: "Good",
    city_type: "State Capital / Hill",
    arsenic_as_pct: 8,
    chromium_cr_pct: 14,
    lead_pb_pct: 30,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 16,
    copper_cu_pct: 16,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 15,
    cod_exceedance_pct: 14,
    do_exceedance_pct: 10,
    ph_exceedance_pct: 15,
    tds_exceedance_pct: 19,
    primary_pollutant_source: "Urban runoff + mining legacy",
    key_heavy_metal: "Lead",
  },
  {
    location_name: "Tura",
    location_type: "City",
    state_ut: "Meghalaya",
    lng: 90.2,
    lat: 25.51,
    surface_water_pollution_pct: 34,
    groundwater_pollution_pct: 32,
    risk_level: "Moderate",
    city_type: "Hill / Mining",
    arsenic_as_pct: 10,
    chromium_cr_pct: 14,
    lead_pb_pct: 32,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 16,
    copper_cu_pct: 12,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 29,
    cod_exceedance_pct: 32,
    do_exceedance_pct: 23,
    ph_exceedance_pct: 18,
    tds_exceedance_pct: 28,
    primary_pollutant_source: "Coal mining runoff (acid drainage)",
    key_heavy_metal: "Lead",
  },
  {
    location_name: "Agartala",
    location_type: "City",
    state_ut: "Tripura",
    lng: 91.29,
    lat: 23.83,
    surface_water_pollution_pct: 22,
    groundwater_pollution_pct: 26,
    risk_level: "Moderate",
    city_type: "State Capital",
    arsenic_as_pct: 34,
    chromium_cr_pct: 12,
    lead_pb_pct: 16,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 20,
    cod_exceedance_pct: 19,
    do_exceedance_pct: 14,
    ph_exceedance_pct: 17,
    tds_exceedance_pct: 24,
    primary_pollutant_source: "Shallow aquifer + urban runoff",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "Port Blair",
    location_type: "City",
    state_ut: "Andaman and Nicobar",
    lng: 92.75,
    lat: 11.62,
    surface_water_pollution_pct: 14,
    groundwater_pollution_pct: 16,
    risk_level: "Good",
    city_type: "UT Capital / Island",
    arsenic_as_pct: 6,
    chromium_cr_pct: 14,
    lead_pb_pct: 16,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 18,
    copper_cu_pct: 30,
    nickel_ni_pct: 8,
    bod_exceedance_pct: 8,
    cod_exceedance_pct: 11,
    do_exceedance_pct: 11,
    ph_exceedance_pct: 6,
    tds_exceedance_pct: 13,
    primary_pollutant_source: "Island urban runoff",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Kavaratti",
    location_type: "City",
    state_ut: "Lakshadweep",
    lng: 72.64,
    lat: 10.57,
    surface_water_pollution_pct: 10,
    groundwater_pollution_pct: 12,
    risk_level: "Good",
    city_type: "UT Capital / Island",
    arsenic_as_pct: 6,
    chromium_cr_pct: 12,
    lead_pb_pct: 14,
    cadmium_cd_pct: 8,
    zinc_zn_pct: 18,
    copper_cu_pct: 34,
    nickel_ni_pct: 8,
    bod_exceedance_pct: 12,
    cod_exceedance_pct: 12,
    do_exceedance_pct: 6,
    ph_exceedance_pct: 13,
    tds_exceedance_pct: 5,
    primary_pollutant_source: "Island — minimal pollution",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Puducherry",
    location_type: "City",
    state_ut: "Puducherry",
    lng: 79.81,
    lat: 11.94,
    surface_water_pollution_pct: 27,
    groundwater_pollution_pct: 29,
    risk_level: "Moderate",
    city_type: "UT Capital / Coastal",
    arsenic_as_pct: 8,
    chromium_cr_pct: 30,
    lead_pb_pct: 18,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 16,
    copper_cu_pct: 14,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 21,
    cod_exceedance_pct: 24,
    do_exceedance_pct: 22,
    ph_exceedance_pct: 11,
    tds_exceedance_pct: 24,
    primary_pollutant_source: "Coastal industry + urban runoff",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Daman",
    location_type: "City",
    state_ut: "Dadra and Nagar Haveli and Daman and Diu",
    lng: 72.83,
    lat: 20.4,
    surface_water_pollution_pct: 38,
    groundwater_pollution_pct: 36,
    risk_level: "Moderate",
    city_type: "UT / Industrial",
    arsenic_as_pct: 10,
    chromium_cr_pct: 20,
    lead_pb_pct: 18,
    cadmium_cd_pct: 28,
    zinc_zn_pct: 12,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 36,
    cod_exceedance_pct: 41,
    do_exceedance_pct: 28,
    ph_exceedance_pct: 20,
    tds_exceedance_pct: 35,
    primary_pollutant_source: "Industrial estates & coastal discharge",
    key_heavy_metal: "Cadmium",
  },
  {
    location_name: "Silvassa",
    location_type: "City",
    state_ut: "Dadra and Nagar Haveli and Daman and Diu",
    lng: 73.01,
    lat: 20.27,
    surface_water_pollution_pct: 44,
    groundwater_pollution_pct: 40,
    risk_level: "Critical",
    city_type: "Industrial",
    arsenic_as_pct: 8,
    chromium_cr_pct: 34,
    lead_pb_pct: 18,
    cadmium_cd_pct: 12,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 41,
    cod_exceedance_pct: 42,
    do_exceedance_pct: 31,
    ph_exceedance_pct: 26,
    tds_exceedance_pct: 40,
    primary_pollutant_source: "Textile & chemical estates",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Ajmer",
    location_type: "City",
    state_ut: "Rajasthan",
    lng: 74.64,
    lat: 26.45,
    surface_water_pollution_pct: 32,
    groundwater_pollution_pct: 37,
    risk_level: "Moderate",
    city_type: "Urban",
    arsenic_as_pct: 22,
    chromium_cr_pct: 16,
    lead_pb_pct: 18,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 16,
    copper_cu_pct: 14,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 30,
    cod_exceedance_pct: 35,
    do_exceedance_pct: 24,
    ph_exceedance_pct: 18,
    tds_exceedance_pct: 33,
    primary_pollutant_source: "Hard groundwater + urban runoff",
    key_heavy_metal: "Fluoride",
  },
  {
    location_name: "Moradabad",
    location_type: "City",
    state_ut: "Uttar Pradesh",
    lng: 78.77,
    lat: 28.84,
    surface_water_pollution_pct: 53,
    groundwater_pollution_pct: 47,
    risk_level: "Extreme",
    city_type: "Industrial (Brassware)",
    arsenic_as_pct: 8,
    chromium_cr_pct: 16,
    lead_pb_pct: 20,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 20,
    copper_cu_pct: 24,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 52,
    cod_exceedance_pct: 57,
    do_exceedance_pct: 40,
    ph_exceedance_pct: 30,
    tds_exceedance_pct: 39,
    primary_pollutant_source: "Brass polishing & electroplating (Ramganga)",
    key_heavy_metal: "Copper",
  },
  {
    location_name: "Firozabad",
    location_type: "City",
    state_ut: "Uttar Pradesh",
    lng: 78.4,
    lat: 27.15,
    surface_water_pollution_pct: 46,
    groundwater_pollution_pct: 42,
    risk_level: "Critical",
    city_type: "Industrial (Glass)",
    arsenic_as_pct: 10,
    chromium_cr_pct: 16,
    lead_pb_pct: 34,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 10,
    nickel_ni_pct: 6,
    bod_exceedance_pct: 46,
    cod_exceedance_pct: 49,
    do_exceedance_pct: 35,
    ph_exceedance_pct: 27,
    tds_exceedance_pct: 33,
    primary_pollutant_source: "Glass & bangle industry",
    key_heavy_metal: "Lead",
  },
  {
    location_name: "Aligarh",
    location_type: "City",
    state_ut: "Uttar Pradesh",
    lng: 78.09,
    lat: 27.88,
    surface_water_pollution_pct: 44,
    groundwater_pollution_pct: 41,
    risk_level: "Critical",
    city_type: "Industrial (Lock)",
    arsenic_as_pct: 8,
    chromium_cr_pct: 18,
    lead_pb_pct: 18,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 12,
    nickel_ni_pct: 20,
    bod_exceedance_pct: 38,
    cod_exceedance_pct: 47,
    do_exceedance_pct: 37,
    ph_exceedance_pct: 25,
    tds_exceedance_pct: 36,
    primary_pollutant_source: "Lock & electroplating units",
    key_heavy_metal: "Nickel",
  },
  {
    location_name: "Saharanpur",
    location_type: "City",
    state_ut: "Uttar Pradesh",
    lng: 77.55,
    lat: 29.97,
    surface_water_pollution_pct: 42,
    groundwater_pollution_pct: 40,
    risk_level: "Critical",
    city_type: "Industrial (Paper)",
    arsenic_as_pct: 8,
    chromium_cr_pct: 30,
    lead_pb_pct: 20,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 16,
    copper_cu_pct: 12,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 35,
    cod_exceedance_pct: 40,
    do_exceedance_pct: 34,
    ph_exceedance_pct: 17,
    tds_exceedance_pct: 35,
    primary_pollutant_source: "Paper & pulp effluent (Hindon)",
    key_heavy_metal: "Chromium",
  },
  {
    location_name: "Rae Bareli",
    location_type: "City",
    state_ut: "Uttar Pradesh",
    lng: 81.24,
    lat: 26.23,
    surface_water_pollution_pct: 30,
    groundwater_pollution_pct: 38,
    risk_level: "Moderate",
    city_type: "Urban / Rail",
    arsenic_as_pct: 34,
    chromium_cr_pct: 12,
    lead_pb_pct: 18,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 14,
    copper_cu_pct: 8,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 24,
    cod_exceedance_pct: 28,
    do_exceedance_pct: 24,
    ph_exceedance_pct: 12,
    tds_exceedance_pct: 29,
    primary_pollutant_source: "Shallow aquifer + rail workshop",
    key_heavy_metal: "Arsenic",
  },
  {
    location_name: "Bareilly",
    location_type: "City",
    state_ut: "Uttar Pradesh",
    lng: 79.42,
    lat: 28.37,
    surface_water_pollution_pct: 39,
    groundwater_pollution_pct: 41,
    risk_level: "Critical",
    city_type: "Urban / Industrial",
    arsenic_as_pct: 8,
    chromium_cr_pct: 30,
    lead_pb_pct: 20,
    cadmium_cd_pct: 10,
    zinc_zn_pct: 16,
    copper_cu_pct: 12,
    nickel_ni_pct: 4,
    bod_exceedance_pct: 36,
    cod_exceedance_pct: 37,
    do_exceedance_pct: 27,
    ph_exceedance_pct: 24,
    tds_exceedance_pct: 38,
    primary_pollutant_source: "Ramganga + minor industry",
    key_heavy_metal: "Chromium",
  }
];

/* ---------- State-level risk aggregation (avg surface pollution) ---------- */
export const stateRiskData: Record<string, number> = (() => {
  const acc: Record<string, { sum: number; n: number }> = {};
  for (const loc of locations) {
    const s = loc.state_ut;
    if (!acc[s]) acc[s] = { sum: 0, n: 0 };
    acc[s].sum += loc.surface_water_pollution_pct;
    acc[s].n += 1;
  }
  const out: Record<string, number> = {};
  for (const [k, v] of Object.entries(acc)) out[k] = Math.round(v.sum / v.n);
  return out;
})();

/* Manual fill for states/UTs without a listed city (map completeness) */
const STATE_FALLBACK: Record<string, number> = {
  "Andhra Pradesh": 36, "Arunachal Pradesh": 13, "Assam": 31, "Bihar": 36,
  "Chhattisgarh": 42, "Delhi": 60, "Goa": 22, "Gujarat": 51, "Haryana": 41,
  "Himachal Pradesh": 23, "Jharkhand": 48, "Karnataka": 34, "Kerala": 25,
  "Madhya Pradesh": 37, "Maharashtra": 41, "Manipur": 16, "Meghalaya": 25,
  "Mizoram": 11, "Nagaland": 18, "Odisha": 40, "Punjab": 42, "Rajasthan": 36,
  "Sikkim": 9, "Tamil Nadu": 45, "Telangana": 36, "Tripura": 22,
  "Uttar Pradesh": 52, "Uttarakhand": 26, "West Bengal": 51,
  "Andaman and Nicobar": 14, "Chandigarh": 28,
  "Dadra and Nagar Haveli and Daman and Diu": 40,
  "Jammu and Kashmir": 20, "Ladakh": 11, "Lakshadweep": 10, "Puducherry": 27,
};
for (const [k, v] of Object.entries(STATE_FALLBACK)) {
  if (stateRiskData[k] === undefined) stateRiskData[k] = v;
}
